<?php

use Illuminate\Database\Seeder;

class TinTucSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('TinTuc')->insert([
            ['TieuDe' => 'Man City “vô đối 1”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Man-City-vo-doi-de-vo-giac-mo1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 1],
            ['TieuDe' => 'Man City “vô đối 2”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Man-City-vo-doi-de-vo-giac-mo2', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 1],
            ['TieuDe' => 'Man City “vô đối 3”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Man-City-vo-doi-de-vo-giac-mo3', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 1],
            ['TieuDe' => 'Man City “vô đối 4”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Man-City-vo-doi-de-vo-giac-mo4', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 1],
            ['TieuDe' => 'Man City “vô đối 5”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Man-City-vo-doi-de-vo-giac-mo5', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 1],
            ['TieuDe' => 'Man City “vô đối 6”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Man-City-vo-doi-de-vo-giac-mo6', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 1],
            ['TieuDe' => 'Man City “vô đối 7”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Man-City-vo-doi-de-vo-giac-mo7', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 1],
            ['TieuDe' => 'Man City “vô đối 8”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Man-City-vo-doi-de-vo-giac-mo8', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 1],
            ['TieuDe' => 'Man City “vô đối 9”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Man-City-vo-doi-de-vo-giac-mo9', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 1],
            ['TieuDe' => 'Man City “vô đối 10”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Man-City-vo-doi-de-vo-giac-mo10', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 1],

            ['TieuDe' => 'Tin vắn bóng đá 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Tin-van-bong-da-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 2],
            ['TieuDe' => 'Tin vắn bóng đá 2”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Tin-van-bong-da-2', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 2],
            ['TieuDe' => 'Tin vắn bóng đá 3”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Tin-van-bong-da-3', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 2],
            ['TieuDe' => 'Tin vắn bóng đá 4”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Tin-van-bong-da-4', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 2],
            ['TieuDe' => 'Tin vắn bóng đá 5”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Tin-van-bong-da-5', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 2],

            ['TieuDe' => 'Bóng đá việt nam 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Bong-da-viet-nam-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 3],
            ['TieuDe' => 'Bóng đá việt nam 2”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Bong-da-viet-nam-2', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 3],
            ['TieuDe' => 'Bóng đá việt nam 3”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Bong-da-viet-nam-3', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 3],
            ['TieuDe' => 'Bóng đá việt nam 4”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Bong-da-viet-nam-4', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 3],
            ['TieuDe' => 'Bóng đá việt nam 5”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Bong-da-viet-nam-5', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 3],

            ['TieuDe' => 'Top ghi bàn 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Top-ghi-ban-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 4],
            ['TieuDe' => 'Top ghi bàn 2”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Top-ghi-ban-2', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 4],
            ['TieuDe' => 'Top ghi bàn 3”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Top-ghi-ban-3', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 4],
            ['TieuDe' => 'Top ghi bàn 4”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Top-ghi-ban-4', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 4],
            ['TieuDe' => 'Top ghi bàn 5”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Top-ghi-ban-5', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 4],

            ['TieuDe' => 'Điểm nóng 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Diem-nong-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 5],
            ['TieuDe' => 'Điểm nóng 2”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Diem-nong-2', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 5],
            ['TieuDe' => 'Điểm nóng 3”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Diem-nong-3', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 5],
            ['TieuDe' => 'Điểm nóng 4”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Diem-nong-4', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 5],
            ['TieuDe' => 'Điểm nóng 5”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Diem-nong-5', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 5],

            ['TieuDe' => 'Quân sự 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Quan-su-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 6],
            ['TieuDe' => 'Quân sự 2”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Quan-su-2', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 6],
            ['TieuDe' => 'Quân sự 3”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Quan-su-3', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 6],
            ['TieuDe' => 'Quân sự 4”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Quan-su-4', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 6],
            ['TieuDe' => 'Quân sự 5”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Quan-su-5', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 6],

            ['TieuDe' => 'Hồ sơ 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Ho-so-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 7],
            ['TieuDe' => 'Hồ sơ 2”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Ho-so-2', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 7],
            ['TieuDe' => 'Hồ sơ 3”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Ho-so-3', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 7],
            ['TieuDe' => 'Hồ sơ 4”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Ho-so-4', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 7],
            ['TieuDe' => 'Hồ sơ 5”: Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Ho-so-5', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 7],

            ['TieuDe' => 'Thế giới động vật 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'The-gioi-dong-vat-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 8],


            ['TieuDe' => 'Tin tức thời trang 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Tin-tuc-thoi-trang-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 9],

            ['TieuDe' => 'Người mẫu - Hoa hậu 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Nguoi-mau-Hoa-hau-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 10],

            ['TieuDe' => 'Thế giới thời trang 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'The-gioi-thoi-trang-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 11],

            ['TieuDe' => 'Trang sức 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Trang-suc-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 12],

            ['TieuDe' => 'Giầy - dép 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Giay-dep-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 13],

            ['TieuDe' => 'Vụ án nổi tiếng 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Vu-an-noi-tieng-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 14],

            ['TieuDe' => 'Kỳ án thế giới 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Ky-an-the-gioi-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 15],

            ['TieuDe' => 'Cảnh giác 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Canh-giac-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 16],

            ['TieuDe' => 'Phóng sự 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Phong-su-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 17],

            ['TieuDe' => 'Món ngon mỗi ngày 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Mon-ngon-moi-ngay-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 18],

            ['TieuDe' => 'Đặc sản 3 miền 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Dac-san-3-mien-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 19],

            ['TieuDe' => 'Tin tức Ẩm thực 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Tin-tuc-Am-thuc-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 20],

            ['TieuDe' => 'Đặt ăn tại nhà qua điện thoại 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Dat-an-tai-nha-qua-dien-thoai-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 21],

            ['TieuDe' => 'Răng khỏe đẹp 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Rang-khoe-dep-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 22],

            ['TieuDe' => 'Thẩm mỹ viện 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Tham-my-vien-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 23],

            ['TieuDe' => 'Trị mụn và nấm da 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Tri-mun-va-nam-da-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 24],

            ['TieuDe' => 'Trang điểm 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Trang-diem-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 25],

            ['TieuDe' => 'Người mẫu - Hoa hậu 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Nguoi-mau-Hoa-hau-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 26],

            ['TieuDe' => 'Thế giới thời trang 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'The-gioi-thoi-trang-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 27],

            ['TieuDe' => 'Trang sức 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Trang-suc-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 28],

            ['TieuDe' => 'Giầy - dép 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Giay-dep-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 29],

            ['TieuDe' => 'Vụ án nổi tiếng 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Vu-an-noi-tieng-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 30],

            ['TieuDe' => 'Kỳ án thế giới 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Ky-an-the-gioi-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 31],

            ['TieuDe' => 'Cảnh giác 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Canh-giac-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 32],

            ['TieuDe' => 'Phóng sự 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Phong-su-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 33],

            ['TieuDe' => 'Món ngon mỗi ngày 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Mon-ngon-moi-ngay-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 34],

            ['TieuDe' => 'Đặc sản 3 miền 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Dac-san-3-mien-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 35],

            ['TieuDe' => 'Tin tức Ẩm thực 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Tin-tuc-Am-thuc-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 36],

            ['TieuDe' => 'Đặt ăn tại nhà qua điện thoại 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Dat-an-tai-nha-qua-dien-thoai-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 37],

            ['TieuDe' => 'Răng khỏe đẹp 1": Dễ vỡ giấc mơ “ăn 4” trong 1 tuần', 'TieuDeKhongDau' => 'Rang-khoe-dep-1', 'TomTat' => 'Một Man City kiệt sức có thể tan vỡ giấc mơ ăn 4 trong vòng 1 tuần.', 'NoiDung' => 'Nếu Man City có ý định đoạt một cú ăn 4 không tưởng trong mùa giải này, đây sẽ là tuần lễ mang tính định đoạt với thầy trò Pep Guardiola, ít nhất là ở mặt trận trong nước bởi Champions League sẽ đến sau.', 'Hinh' => 'http://', 'NoiBat' => 1, 'SoLuotXem' => 10, 'idLoaiTin' => 38],

        ]);
    }
}
